Controllers/ClinicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using physioCard.Domain;
using physioCard.Services;

namespace physioCard.Controllers
{
    [Authorize]
    public class ClinicController : Controller
    {
        private readonly IClinicService _clinicService;
        private readonly IDoctorClinicService _doctorClinicService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly DashBoardController _dashBoardController;
        public ClinicController(IClinicService clinicService, IDoctorClinicService doctorClinicService, IWebHostEnvironment webHostEnvironment, DashBoardController dashBoardController)
        {
            _clinicService = clinicService;
            _doctorClinicService = doctorClinicService;
            _webHostEnvironment = webHostEnvironment;
            _dashBoardController = dashBoardController;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> AddDoctorClinic()
        {
            int did = (int)HttpContext.Session.GetInt32("docID");
            ViewBag.did = did;
            ViewBag.data = await _dashBoardController.getProfileAsync(ViewBag.did);
            ViewBag.clinics = new MultiSelectList(await _clinicService.GetAllAsync(did), "clinicID", "name");
            bool IsClinic = await _doctorClinicService.IsClinicAsync(ViewBag.did);
            ViewData["IsClinic"] = IsClinic;
            return View();
        }

        public async Task<IActionResult> getClinicByID(int id)
        {
            Clinic clinic = await _clinicService.GetByClinicID(id);
            //var s = Json(clinic);
            return Json(clinic);
        }

        public async Task<IActionResult> GetByClinicID(int id)
        {
            try
            {
                Clinic clinic = await _clinicService.GetByClinicID(id);
                int did = (int)HttpContext.Session.GetInt32("docID");
                ViewBag.data = await _dashBoardController.getProfileAsync(did);
                return View(clinic);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to show Clinic. " +
                                             "Try Again, and if the problem persists" +
                                             "See your system administrator.");
            }
            return View();
        }

        public async Task<IActionResult> RemoveClinic(int id)
        {
            try
            {
                await _doctorClinicService.RemoveAsync(id);
                int did = (int)HttpContext.Session.GetInt32("docID");
                bool IsClinic = await _doctorClinicService.IsClinicAsync(did);
                if (IsClinic)
                {
                    return RedirectToAction("ViewProfile", "Doctor");
                }
                else
                {
                    return RedirectToAction(nameof(AddDoctorClinic));
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to Delete Clinic. " +
                                             "Try Again, and if the problem persists" +
                                             "See your system administrator.");
            }
            return View();
        }

        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public async Task<IActionResult> AddDoctorClinic(Doctor_Clinic doctor_clinic)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _doctorClinicService.CreateDoctorClinicAsync(doctor_clinic);
                    return RedirectToAction("DashBoard", "DashBoard");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to add clinic/clinics in doctor. " +
                                             "Try Again, and if the problem persists" +
                                             "See you system administrator.");
            }
            int did = (int)HttpContext.Session.GetInt32("docID");
            ViewBag.clinics = new MultiSelectList(await _clinicService.GetAllAsync(did), "clinicID", "name");
            return View();
        }
        public async Task<IActionResult> CreateClinic()
        {
            int did = (int)HttpContext.Session.GetInt32("docID");
            ViewBag.data = await _dashBoardController.getProfileAsync(did);
            bool IsClinic = await _doctorClinicService.IsClinicAsync(did);
            ViewData["IsClinic"] = IsClinic;
            return View();
        }

        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public async Task<IActionResult> CreateClinic(Clinic clinic)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var headSign = HttpContext.Request.Form.Files.GetFile("head_signature_img");
                    var headSignFolder = "Clinic/head_signature/";
                    headSignFolder += Guid.NewGuid().ToString().Substring(0, 8) + "_" + headSign.FileName;
                    string headSignServer = Path.Combine(_webHostEnvironment.WebRootPath, headSignFolder);
                    await headSign.CopyToAsync(new FileStream(headSignServer, FileMode.Create));
                    clinic.head_signature = headSignFolder;

                    var logoImg = HttpContext.Request.Form.Files.GetFile("logo_img");
                    var logoFolder = "Clinic/logo/";
                    logoFolder += Guid.NewGuid().ToString().Substring(0, 8) + "_" + logoImg.FileName;
                    string logoServer = Path.Combine(_webHostEnvironment.WebRootPath, logoFolder);
                    await logoImg.CopyToAsync(new FileStream(logoServer, FileMode.Create));
                    clinic.logo = logoFolder;

                    await _clinicService.CreateClinicAsync(clinic);
                    return RedirectToAction(nameof(AddDoctorClinic));
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to Add Clinic. " +
                                             "Try Again, and if the problem persists" +
                                             "See you system administrator.");
            }
            return View(clinic);
        }
    }
}

Controllers/InvoiceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using physioCard.Domain;
using physioCard.Services;
using physioCard.wwwroot.lib.Mail;
using System.Collections.Generic;
using System.Net.Mail;

namespace physioCard.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private readonly IInvoiceService _invoiceService;
        private readonly DashBoardController _dashBoardController;
        private readonly IAppointmentService _appointmentService;
        private readonly IPatientService _patientService;
        private readonly IClinicService _clinicService;
        private readonly IDoctorService _doctorService;

        public InvoiceController(IInvoiceService invoiceService, DashBoardController dashBoardController, IAppointmentService appointmentService, IPatientService patientService, IClinicService clinicService, IDoctorService doctorService)
        {
            _invoiceService = invoiceService;
            _dashBoardController = dashBoardController;
            _appointmentService = appointmentService;
            _patientService = patientService;
            _clinicService = clinicService;
            _doctorService = doctorService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> generateInvoice()
        {
            int did = (int)HttpContext.Session.GetInt32("docID");
            ViewBag.data = await _dashBoardController.getProfileAsync(did);
            List<Patient> patients = await _patientService.getallpatient(did);
            List<Patient> ipatients = new List<Patient>();
            foreach (var patient in patients)
            {
                Clinic clinic = await _clinicService.GetByClinicID(patient.clinicid);
                patient.clinicname = clinic.name;
                List<Appointment> appointments = await _invoiceService.getAppointmentbyPatientID(patient.patientID);
                if (appointments.Count > 0)
                {
                    ipatients.Add(patient);
                }
            }
            ViewBag.patients = ipatients;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> getAppointmentbyPatientID(int patientID)
        {
            List<Appointment> appointments = await _invoiceService.getAppointmentbyPatientID(patientID);
            return Json(appointments);
        }

        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public async Task<IActionResult> createInvoice(int[] appointment_ids, int patientID, double discount)
        {
            try
            {
                if (appointment_ids.Count() > 0)
                {
                    int did = (int)HttpContext.Session.GetInt32("docID");
                    ViewBag.data = await _dashBoardController.getProfileAsync(did);
                    List<Appointment> appointments = new List<Appointment>();
                    foreach (int id in appointment_ids)
                    {
                        Appointment appointment = await _appointmentService.getAppointmentByID(id);
                        appointments.Add(appointment);
                    }
                    Invoice invoice = new Invoice();
                    Random random = new Random();
                    invoice.invoiceNo = DateTime.Now.ToString("yyyyMMdd") + patientID.ToString() + random.Next(00, 99).ToString();
                    invoice.patientID = patientID;
                    invoice.doctorID = did;
                    invoice.invoice_date = DateTime.Now;
                    invoice.total_appointment = appointments.Count;
                    invoice.discount = discount;
                    invoice.istart_date = appointments[0].date_start;
                    invoice.iend_date = appointments[appointments.Count - 1].date_start;

                    foreach (var item in appointments)
                    {
                        invoice.total_amount = invoice.total_amount + item.cost;
                    }
                    double discountamount = (invoice.discount * invoice.total_amount) / 100;
                    invoice.gross_amount = invoice.total_amount - discountamount;

                    bool status = await _invoiceService.createInvoice(invoice);

                    if (status)
                    {
                        await _invoiceService.updateAppointmentInvoiceStatus(appointments);
                        return RedirectToAction("yourInvoice", new { ino = invoice.invoiceNo });
                    }
                    else
                    {
                        List<Patient> patients = await _patientService.getallpatient(did);
                        foreach (var patient in patients)
                        {
                            Clinic clinic = await _clinicService.GetByClinicID(patient.clinicid);
                            patient.clinicname = clinic.name;
                        }
                        ViewBag.patients = patients;
                        ViewBag.invoice = false;
                        return View("generateInvoice");
                    }
                }
                return RedirectToAction("generateInvoice");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to create invoice. " +
                "Try Again, and if the problem persists" +
                "See your system administrator.");
                return View();
            }
        }

        public async Task<IActionResult> showInvoice(String ino)
        {
            int did = (int)HttpContext.Session.GetInt32("docID");
            ViewBag.data = await _dashBoardController.getProfileAsync(did);
            Doctor doctor = await _doctorService.GetByIDAsync(did);
            Invoice invoice = await _invoiceService.getInvoiceByID(ino);
            Patient patient = await _patientService.getpatient(invoice.patientID);
            Clinic clinic = await _clinicService.GetByClinicID(patient.clinicid);
            List<Appointment> appointments = await _invoiceService.getAppointmentsinInvoice(invoice);
            foreach (var item in appointments)
            {
                item.endtime = item.starttime.Add(item.sessiontime.TimeOfDay);
            }

            ViewBag.appointments = appointments;
            ViewBag.invoice = invoice;
            ViewBag.patient = patient;
            ViewBag.clinic = clinic;
            ViewBag.doctor = doctor;
            return View();
        }

        public async Task<IActionResult> yourInvoice(String ino)
        {
            int did = (int)HttpContext.Session.GetInt32("docID");
            ViewBag.data = await _dashBoardController.getProfileAsync(did);
            Doctor doctor = await _doctorService.GetByIDAsync(did);
            Invoice invoice = await _invoiceService.getInvoiceByID(ino);
            Patient patient = await _patientService.getpatient(invoice.patientID);
            Clinic clinic = await _clinicService.GetByClinicID(patient.clinicid);
            List<Appointment> appointments = await _invoiceService.getAppointmentsinInvoice(invoice);
            foreach (var item in appointments)
            {
                item.endtime = item.starttime.Add(item.sessiontime.TimeOfDay);
            }

            string to = patient.email;
            string subject = "Your Invoice Dated On " + DateTime.Now.ToString("dd-MM-yyyy");
            string body = sendmail.CreateBody(invoice, patient, clinic, doctor);
            AlternateView alternateViewLogo = _invoiceService.CreateAlternateViewofLogo(body, clinic);
            AlternateView alternateViewSign = _invoiceService.CreateAlternateViewofSign(body, clinic);
            bool mailStatus = sendmail.sendingEmailWithImage(to, subject, body, alternateViewLogo, alternateViewSign);

            ViewBag.appointments = appointments;
            ViewBag.invoice = invoice;
            ViewBag.patient = patient;
            ViewBag.clinic = clinic;
            ViewBag.doctor = doctor;
            return View();
        }

        public async Task<IActionResult> paymentStatus()
        {
            int did = (int)HttpContext.Session.GetInt32("docID");
            ViewBag.data = await _dashBoardController.getProfileAsync(did);
            List<Invoice> invoice = await _invoiceService.getAllInvoiceMonthly(did);
            ViewBag.invoice = invoice;
            return View();
        }

        [HttpPost]
        public async Task<bool> payStatusEdit(bool status, int invoiceID)
        {
            bool mystatus = await _invoiceService.payStatusEdit(status, invoiceID);
            return status;
        }

        public async Task<IActionResult> seeAllPendingInvoice()
        {
            int did = (int)HttpContext.Session.GetInt32("docID");
            ViewBag.data = await _dashBoardController.getProfileAsync(did);
            List<Invoice> invoice = await _invoiceService.seeAllPendingInvoice(did);
            ViewBag.allinvoice = invoice;
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - physioCard</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Smooch&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/physioCard.styles.css" asp-append-version="true" />
</head>
<body>
    @*<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">physioCard</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="DashBoard" asp-action="DashBoard">DashBoard</a>
    </li>
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
    </ul>
    </div>
    @if (ViewBag.data[0] != null)
    {
    <div>
    <ul class="nav nav-pills">
    <li class="nav-item dropdown">
    <a class="nav-link text-black" data-bs-toggle="dropdown" role="button" aria-expanded="false"><img src="~/@ViewBag.data[1]" style="border-radius: 50%" width="40" height="40" /> @ViewBag.data[2]</a>
    <ul class="dropdown-menu">
    <li><a class="dropdown-item" asp-area="" asp-controller="Doctor" asp-action="ViewProfile">View Profile</a></li>
    <li><a class="dropdown-item" asp-area="" asp-controller="Doctor" asp-action="Logout">Log Out</a></li>
    </ul>
    </li>
    </ul>
    </div>
    }
    <div>&nbsp; &nbsp;</div>
    </div>
    </nav>
    </header>*@
    <div class="sidebar">
        <header class="logo_content">
            <div class="logo">
                @*<i class='bx bxl-netlify'></i>*@
                @*<img src="~/fav/favicon-32x32.png" style="padding: 0 10px;" />*@
                <div class="logo_name">PhysioCard</div>
            </div>
            <i class='bx bx-menu' id="btn"></i>
        </header>
        <ul class="nav_list">
            <li>
                <a asp-controller="DashBoard" asp-action="DashBoard" title="Dashboard">
                    <i class='bx bx-home-alt-2'></i>
                    <span class="links_name">Dashboard</span>
                </a>
            </li>
            <li>
                <a asp-controller="Patient" asp-action="addPatient" title="Add Patient">
                    <i class='bx bx-user-plus'></i>
                    <span class="links_name">Add Patient</span>
                </a>
            </li>
            <li>
                <a asp-controller="Patient" asp-action="showPatient" title="Show Patient">
                    <i class='bx bxs-user-account'></i>
                    <span class="links_name">Show Patient</span>
                </a>
            </li>
            <li>
                <a asp-controller="Appointment" asp-action="AppointmentCalendar" title="Appointment Calendar">
                    <i class='bx bx-calendar'></i>
                    <span class="links_name">Appointment Calendar</span>
                </a>
            </li>
            <li>
                <a asp-controller="Appointment" asp-action="FixAppointment" title="Schedule Appointment">
                    <i class='bx bx-calendar-plus'></i>
                    <span class="links_name">Schedule Appointment</span>
                </a>
            </li>
            <li>
                <a asp-controller="Appointment" asp-action="showAppointment" title="Show Appointment">
                    <i class='bx bx-calendar-heart'></i>
                    <span class="links_name">Show Appointment</span>
                </a>
            </li>
            <li>
                <a asp-controller="Attendance" asp-action="showTodaysAppointment" title="Attendance">
                    <i class='bx bxs-user-check'></i>
                    <span class="links_name">Attendance</span>
                </a>
            </li>
            <li>
                <a asp-controller="Invoice" asp-action="generateInvoice" title="Generate Invoice">
                    <i class='bx bx-spreadsheet'></i>
                    <span class="links_name">Generate Invoice</span>
                </a>
            </li>
            <li>
                <a asp-controller="Invoice" asp-action="paymentStatus" title="Payment Status">
                    <i class='bx bx-check-square'></i>
                    <span class="links_name">Payment Status</span>
                </a>
            </li>
            <li>
                <a asp-controller="Clinic" asp-action="AddDoctorClinic" title="Add Clinic">
                    <i class='bx bx-clinic'></i>
                    <span class="links_name">Add Clinic</span>
                </a>
            </li>
            @*<li>
            <a asp-controller="Doctor" asp-action="Changepassword">
            <i class='bx bxs-key'></i>
            <span class="links_name">Change Password</span>
            </a>
            <span id="tooltip">Change Password</span>
            </li>*@
        </ul>
        <div class="profile_content">
            <div class="profile">
                <a class="profile_details" asp-controller="Doctor" asp-action="ViewProfile">
                    <img src="~/@ViewBag.data[1]" />
                    <div class="profile_name">
                        <div class="name">Dr. @ViewBag.data[2]</div>
                    </div>
                </a>
                <a asp-controller="Doctor" asp-action="Logout"><i class='bx bx-log-out-circle' title="Log Out" id="log_out"></i></a>
            </div>
        </div>
    </div>
    <div class="home_content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2022 - physioCard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - physioCard</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />*@
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="~/css/site1.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/physioCard.styles.css" asp-append-version="true" />
</head>
<body>
    @*<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
    <a class="navbar-brand">physioCard</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
    </ul>
    </div>
    </div>
    </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2022 - physioCard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>