Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using physioCard.Domain;
using physioCard.Services;

namespace physioCard.Controllers
{
    [Authorize]
    public class DashBoardController : Controller
    {
        private readonly IDoctorClinicService _doctorClinicService;
        private readonly IDoctorService _doctorService;
        private readonly IAppointmentService _appointmentService;
        private readonly IAttendanceService _attendanceService;
        private readonly IPatientService _patientService;
        private readonly IInvoiceService _invoiceService;

        public DashBoardController(IDoctorClinicService doctorClinicService, IDoctorService doctorService, IAttendanceService attendanceService, IAppointmentService appointmentService, IPatientService patientService, IInvoiceService invoiceService)
        {
            _doctorClinicService = doctorClinicService;
            _doctorService = doctorService;
            _attendanceService = attendanceService;
            _appointmentService = appointmentService;
            _patientService = patientService;
            _invoiceService = invoiceService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> DashBoard()
        {
            try
            {
                int did;
                int uid = Int32.Parse(Request.Cookies["uID"]);
                if (uid == 0)
                {
                    did = (int)HttpContext.Session.GetInt32("docID");
                }
                else
                {
                    did = uid;
                    HttpContext.Session.SetInt32("docID", did);
                }
                bool IsClinic = await _doctorClinicService.IsClinicAsync(did);
                if (IsClinic == false)
                    return RedirectToAction("addDoctorClinic", "Clinic");
                else
                {
                    ViewBag.data = await getProfileAsync(did);
                    List<Appointment> appointments = await _attendanceService.getTodaysAppointment(did);
                    foreach (var item in appointments)
                    {
                        item.endtime = item.starttime.Add(item.sessiontime.TimeOfDay);
                    }
                    ViewBag.appointment = appointments;
                    List<Patient> patient = await _patientService.getallpatient(did);
                    foreach (Patient item in patient)
                    {
                        if (item.medical_History == null)
                        {
                            item.medical_History = "None";
                        }
                        TimeSpan ts = DateTime.Now - item.dob;
                        int age = (int)ts.TotalDays / 365;
                        item.age = age;
                    }
                    ViewBag.patients = patient;
                    ViewBag.patientCount = await _patientService.getPatientCount(did);
                    ViewBag.appointmentCount = await _appointmentService.getAppointmentCount(did);
                    ViewBag.revenueCount = await _invoiceService.getRevenueCount(did);
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to show dashboard. " +
                "Try Again, and if the problem persists" +
                "See your system administrator.");
            }
            return View();
        }
        public async Task<IActionResult> getYearlyData()
        {
            int did = (int)HttpContext.Session.GetInt32("docID");
            List<revenueModel> rm = await _invoiceService.getYearlyRevenue(did);
            foreach (var item in rm)
            {
                DateTime d = new DateTime(2022, item.monthID, 1);
                item.mName = d.ToString("MMM");
            }
            return Json(rm);
        }

        public async Task<string[]> getProfileAsync(int did)
        {
            Doctor doctor = await _doctorService.GetByIDAsync(did);
            string name = doctor.fname + " " + doctor.lname;
            string[] str = { doctor.docID.ToString(), doctor.photo, name };
            return str;
        }
    }
}

Controllers/DoctorController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using physioCard.Domain;
using physioCard.Services;
using physioCard.wwwroot.lib.Mail;
using physioCard.wwwroot.lib.Securities;
using System.Security.Claims;

namespace physioCard.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorService _doctorService;
        private readonly IClinicService _clinicService;
        private readonly IDoctorClinicService _doctorClinicService;
        private readonly ILoginService _loginService;
        private readonly IWebHostEnvironment _WebHostEnvironment;
        private readonly DashBoardController _dashBoardController;
        public DoctorController(IDoctorService doctorService, IClinicService clinicService, IDoctorClinicService doctorClinicService, ILoginService loginService, IWebHostEnvironment webHostEnvironment, DashBoardController dashBoardController)
        {
            _clinicService = clinicService;
            _doctorService = doctorService;
            _doctorClinicService = doctorClinicService;
            _loginService = loginService;
            _WebHostEnvironment = webHostEnvironment;
            _dashBoardController = dashBoardController;
        }

        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> SignUp()
        {
            //ViewBag.clinicList = new MultiSelectList(await _clinicService.GetAllAsync(), "clinicID", "name");

            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<ActionResult> SignUp(Doctor doctor)
        {
            try
            {
                //ViewBag.cliniclist = new MultiSelectList(await _clinicService.GetAllAsync());
                // checks whether all the built-in and custom validation is applied on all the data or not
                bool emailcheck = await _doctorService.checkemail(doctor.email);
                if (emailcheck)
                {
                    if (ModelState.IsValid)
                    {
                        // gets the file from post request
                        var theFile = HttpContext.Request.Form.Files.GetFile("photo_img");
                        // server location to store the files
                        string folder = "Doctor/photo/";
                        // will add some garbage data in file name
                        folder += Guid.NewGuid().ToString().Substring(0, 8) + "_" + theFile.FileName;
                        // buiding the server path to the uploads directory
                        string serverFolder = Path.Combine(_WebHostEnvironment.WebRootPath, folder);
                        // saving the file
                        await theFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                        // storing file path string
                        doctor.photo = folder;


                        // encrypting the password
                        doctor.password = CustomSecurity.ConvertToEncrypt(doctor.password);


                        // storing data in database
                        await _doctorService.SignUpAsync(doctor);
                        // redirecting page to login page
                        return View(nameof(Login));
                    }
                }
                else
                {
                    ViewBag.error = "YOU WON'T BE ABLE TO REGISTER USING THIS E-MAIL AS IT IS ALREADY REGISTERD. KINDLY USE ANOTHER E-MAIL ID.";
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to Sign Up. " +
                "Try Again, and if the problem persists" +
                "See your system administrator.");
            }


            return View(doctor);
        }
        [Authorize]
        public async Task<ActionResult> EditDoctor()
        {
            int did = (int)HttpContext.Session.GetInt32("docID");
            Doctor doctor = await _doctorService.GetByIDAsync(did);
            ViewBag.data = await _dashBoardController.getProfileAsync(did);
            return View(doctor);
        }
        [Authorize]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<ActionResult> EditDoctor(Doctor doctor)
        {
            try
            {
                if (doctor.photo_img != null)
                {
                    // gets the file from post request
                    var theFile = HttpContext.Request.Form.Files.GetFile("photo_img");
                    // server location to store the files
                    string folder = "Doctor/photo/";
                    // will add some garbage data in file name
                    folder += Guid.NewGuid().ToString().Substring(0, 8) + "_" + theFile.FileName;
                    // buiding the server path to the uploads directory
                    string serverFolder = Path.Combine(_WebHostEnvironment.WebRootPath, folder);
                    // saving the file
                    await theFile.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                    // storing file path string
                    doctor.photo = folder;
                }
                int did = (int)HttpContext.Session.GetInt32("docID");
                doctor.docID = did;
                //ViewBag.data = await _dashBoardController.getProfileAsync(did);
                // checks whether all the built-in and custom validation is applied on all the data or not
                if (ModelState.IsValid)
                {
                    // updating data in database
                    await _doctorService.UpdateDoctorAsync(doctor);
                    // redirecting page to login page
                    return RedirectToAction(nameof(ViewProfile));
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to Update data. " +
                                             "Try Again, and if the problem persists" +
                                             "See you system administrator.");
            }
            return View(doctor);
        }
        [Authorize]
        public async Task<ActionResult> ViewProfile()
        {
            try
            {
                int did = (int)HttpContext.Session.GetInt32("docID");
                Doctor doctor = await _doctorService.GetByIDAsync(did);
                List<Clinic> clinics = await _clinicService.GetByDoctorIDAsync(did);

                if (clinics.Count <= 0)
                {
                    return RedirectToAction("AddDoctorClinic", "Clinic");
                }

                else
                {
                    //Tuple<Doctor, List<Clinic>> tuple = new Tuple<Doctor, List<Clinic>>(doctor, clinics);
                    string[] name = new string[clinics.Count];
                    for (int i = 0; i < clinics.Count; i++)
                    {
                        name[i] = clinics[i].name;
                    }
                    int[] id = new int[clinics.Count];
                    for (int i = 0; i < clinics.Count; i++)
                    {
                        id[i] = clinics[i].clinicID;
                    }
                    ViewBag.cID = id;
                    ViewBag.cName = name;
                    ViewBag.data = await _dashBoardController.getProfileAsync(did);
                    ViewBag.Doctor = doctor;
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to show Profile. " +
                                             "Try Again, and if the problem persists" +
                                             "See your system administrator.");
            }
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Login(Login l)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    l.password = CustomSecurity.ConvertToEncrypt(l.password);
                    int did = await _loginService.LoginAsync(l);
                    ViewBag.did = did;
                    if (did > 0)
                    {
                        HttpContext.Session.SetInt32("docID", did);
                        //FormsAuthentication.SetAuthCookie(did, l.email);
                        //Craeting the Security Context
                        var claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Name, did.ToString()),
                            new Claim(ClaimTypes.Email, l.email),
                        };
                        var identity = new ClaimsIdentity(claims, "MyAuthenticatedCookie");
                        ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(identity);

                        var authProperties = new AuthenticationProperties
                        {
                            IsPersistent = l.rememberMe
                        };

                        var options = new CookieOptions
                        {
                            Expires = DateTime.Now.AddDays(30)
                        };
                        if (l.rememberMe)
                        {
                            Response.Cookies.Append("uID", did.ToString(), options);
                        }
                        else
                        {
                            HttpContext.Response.Cookies.Append("uID", "0", options);
                        }

Views/Doctor/Changepassword.cshtml
@model physioCard.Domain.OTPModel
@*
For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Change Password";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
<link rel="stylesheet" href="~/css/formDesign.css" asp-append-version="true" />
<div class="container">
    <div>
        <div>
            <form asp-action="Changepassword" id="myForm" method="post">
                <div class="headline">
                    <h1>Change Password</h1>
                </div>
                @if (ViewBag.Status == false)
                {
                    <span class="text-danger">@ViewBag.error</span>
                    <br />
                }
                <br />
                <div class="form-group">
                    <div class="form-outline">
                        <input type="password" asp-for="oldpassword" id="password1" class="form-control custom3" placeholder=" " />
                        <label class="form-label">Old Password </label>
                    </div>
                </div>
                @*<div class="row">
                <div class="col-4">
                <span asp-validation-for="password" id="errPwd" class="text-danger"></span>
                </div>
                </div>*@
                <br />
                <div class="form-group">
                    <div class="form-outline">
                        <input type="password" asp-for="password" onchange="return chkPwd()" id="password" class="form-control custom3 pwd" placeholder=" " />
                        <label class="form-label">New Password </label>
                    </div>
                    <span asp-validation-for="password" id="errPwd" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <div class="form-outline">
                        <input type="password" id="Confirmpassword" class="form-control custom3" placeholder=" " asp-for="confirmpassword" />
                        <label class="form-label" asp-for="confirmpassword">Confirm New Password </label>
                    </div>
                    <span id="errConfirmPwd" asp-validation-for="confirmpassword" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-primary" />
                    <a asp-action="Changepassword" class="btn btn-secondary">Reset</a>
                </div>
            </form>
        </div>
    </div>

    @{
        if (ViewBag.Status == true)
        {
            <script>
                swal({
                    title: "Success",
                    text: "Password Changed Successfully. Login Again.",
                    type: "success",
                    timer: 1500,
                    showCancelButton: false,
                    showConfirmButton: false
                });
                window.location.replace("Logout");
            </script>
        }
    }
</div>
<script>
    function chkPwd() {
        var pass = document.querySelector(".pwd");
        var val = pass.value;
        document.getElementById("errPwd").style.color = "#FF0000";
        var error = document.getElementById("errPwd");
        if (!val.match("(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9])") || val.length != 8) {
            error.innerHTML = "RULES FOR PASSWORD: ";
            if (!val.match("^(?=.*[A-Z])")) {
                error.innerHTML += "ONE UPPER-CASE CHARACTER, ";
            }
            if (!val.match("^(?=.*[a-z])")) {
                error.innerHTML += "ONE LOWER-CASE CHARACTER, ";
            }
            if (!val.match("^(?=.*[0-9])")) {
                error.innerHTML += "ONE NUMBER, ";
            }
            if (!val.match("^(?=.*[^a-zA-Z0-9])")) {
                error.innerHTML += "ONE SPECIAL CHARACTER, ";
            }
            if (val.length != 8) {
                error.innerHTML += "LENGTH MUST BE 8";
            }
            if (val == null) {
                error.innerHTML += "ENTER YOUR PASSWORD";
            }
            //pass.value = '';
            return false;
        }
        else {
            error.innerHTML = '';
            return true;
        }
    }
</script>

Views/Doctor/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Index</h1>

Views/Doctor/ViewProfile.cshtml
@model physioCard.Domain.Doctor
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Profile";
}
<link rel="stylesheet" href="~/css/formDesign.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/profileSite.css" asp-append-version="true" />
<div class="container">
    @*<br />
    <h1>My Profile</h1>
    <hr /><br />*@

    <div>
        @*<div class="change-password-flex">
        <div class="change-password-item1"><a asp-controller="Doctor" asp-action="Changepassword" class="btn btn-dark" style="width: 100%">Change Password</a></div>
        </div>
        <br/>*@
        <div class="shadow-sm card p-3 mb-5 rounded">
            <div class="row">
                <div class="col-8">
                    <div class="heading"><span class="material-icons px-2" id="info" style="font-size: 18px;">info</span>Personal Info</div>
                </div>
                <div class="col-4" align="right">
                    @*<a asp-controller="Doctor" asp-action="EditDoctor"><span class="material-icons e-icon btn btn-outline-dark" title="Edit">mode_edit</span></a>
                    <a asp-controller="Doctor" asp-action="Changepassword"><span class="material-icons e-icon btn btn-outline-dark" title="Change Password">key</span></a>*@
                    <a href="#" data-bs-toggle="modal" data-bs-target="#editDoc" data-id="@ViewBag.Doctor.docID"><span class="material-icons e-icon btn btn-outline-dark" title="Edit">mode_edit</span></a>
                    <a asp-controller="Doctor" asp-action="Changepassword"><span class="material-icons e-icon btn btn-outline-dark" title="Change Password">key</span></a>
                </div>
            </div>
            @*<div class="ps-5">*@
            <div class="flex-container">
                <div class="flex-item item1">
                    <a href="../@ViewBag.Doctor.photo">
                        <img src="../@ViewBag.Doctor.photo" @*class="img-fluid"*@ />
                    </a>
                </div>
                <div class="flex-item item2">
                    @*<br />*@
                    <h1>Dr. @ViewBag.Doctor.fname @ViewBag.Doctor.lname</h1>
                    <dl>
                        <dt>Email</dt>
                        <dd>@ViewBag.Doctor.email</dd>
                        <dt>Contact No.</dt>
                        <dd>@ViewBag.Doctor.contactno</dd>
                    </dl>
                </div>
            </div>
            @*</div>*@
        </div>
        <div class="shadow-sm card p-3 mb-5 rounded">
            <div class="heading"><span class="material-icons px-2" id="info" style="font-size: 18px;">info</span>Clinics Info</div>
            <div class="ps-4">
                <ul type="none">
                    @for (int i = 0; i < ViewBag.cID.Length; i++)
                    {
                        <li><a class="text-black mylink" id="delClnc" style="text-decoration: none; font-size: 20px;" href="#" data-bs-toggle="modal" data-bs-target="#delClinic" data-id="@ViewBag.cID[i]">@ViewBag.cName[i]  </a></li>
                    }
                </ul>
            </div>
        </div>
        <div>
            <a asp-controller="DashBoard" asp-action="DashBoard" class="btn"> << Back To DashBoard</a>
        </div>
    </div>
</div>

<!-- Modal For Remove Clinic -->
<div class="modal" id="delClinic" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Clinic Info</h4>
            </div>
            <form method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="flex-container">
                        <div class="flex-item fi1 item1">
                            <a href="" id="logoLink">
                                <img id="logo" style="border-radius : 50%; border: 1px solid #ddd; padding: 5px; width: 200px; height: 200px;" />
                            </a>
                        </div>
                        <div class="flex-item fi2 item2">
                            <h1 id="name" name="name"></h1>
                            <dl>
                                <dt>Address</dt>
                                <dd id="addr" name="address"></dd>
                                <dt>Contact No.</dt>
                                <dd id="contact" name="contactno"></dd>
                                <dt>GST No.</dt>
                                <dd id="Gst" name="GSTno"></dd>
                            </dl>
                        </div>
                    </div>
                    <br />
                    <div class="modal-footer">
                        <div class="form-group">
                            <input type="submit" value="Delete" id="DelClinic" class="btn btn-danger" />
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal For Update Doctor -->
<div class="modal" id="editDoc" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Update Your Info</h4>
            </div>
            <form asp-action="EditDoctor" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <div class="form-outline">
                                    <input asp-for="fname" class="form-control" placeholder=" " id="custom" value="@ViewBag.Doctor.fname" />
                                    <label class="form-label">First Name </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <div class="form-outline">
                                    <input asp-for="lname" class="form-control" id="custom" placeholder=" " value="@ViewBag.Doctor.lname" />
                                    <label class="form-label">Last Name </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span asp-validation-for="fname" class="text-danger"></span>
                        </div>
                        <div class="col-6">
                            <span asp-validation-for="lname" class="text-danger"></span>
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="form-outline">
                            <input asp-for="email" class="form-control" placeholder=" " id="custom" value="@ViewBag.Doctor.email" />
                            <label class="form-label">E-mail </label>
                        </div>
                        <span asp-validation-for="email" class="text-danger"></span>
                    </div>
                    <br />
                    <input type="hidden" asp-for="password" value="Abc@1234" />
                    <input type="hidden" asp-for="confirmPassword" value="Abc@1234" />
                    <input type="hidden" asp-for="photo" value="@ViewBag.Doctor.photo" />
                    <div class="form-group">
                        <div class="form-outline">
                            <input asp-for="contactno" class="form-control" placeholder=" " id="custom" value="@ViewBag.Doctor.contactno" />
                            <label asp-for="contactno" class="form-label">Contact No </label>
                        </div>
                        <span asp-validation-for="contactno" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="form-outline">
                            <input  asp-for="photo_img" type="file" id="photo_img" onchange="return chkImg()" accept="image/*" class="form-control" />
                            <label asp-for="photo_img" class="form-label">Profile Picture </label>
                        </div>
                        <span asp-validation-for="photo_img" id="errImg" class="text-danger"></span><br />
                        <div id="prevImg"><img src="../@ViewBag.Doctor.photo" width="150" /></div>
                    </div>
                    <br />
                    <div class="modal-footer">
                        <div class="form-group">
                            <input type="submit" value="Edit" class="btn btn-primary" />
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<style>
    a.mylink:hover::after {
        background: url(https://fonts.gstatic.com/s/i/materialicons/delete/v17/20px.svg);
        background-size: 20px 20px;
        display: inline-block;
        width: 20px;
        height: 20px;
        content: "";
    }

    .fi2 {
        max-width: 100px;
        margin: 20px 50px 0;
    }
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

@*client side validation on image and password*@
<script>
    $(document).ready(function() {
        $('ul .mylink').on('click', function() {
            var id = $(this).data("id");
            console.log(id);
            $.ajax({
                type: 'POST',
                url: '/Clinic/getClinicByID/',
                data: { "id": id },
                success: function(response) {
                    $("#logo").attr("src", "../../" + response.logo);
                    console.log(response.logo + " " + response.name + " " + response.address + " " + response.contactno + " ");
                    console.log(response.gsTno);
                    $("#logoLink").attr("href", "../../" + response.logo);

                    document.getElementById("name").innerHTML = response.name;
                    document.getElementById("addr").innerHTML = response.address;
                    document.getElementById("contact").innerHTML = response.contactno;
                    document.getElementById("Gst").innerHTML = response.gsTno;

                    $('#DelClinic').on('click', function() {
                        $.ajax({
                            url: '/Clinic/RemoveClinic/',
                            data: { "id": response.clinicID },
                            success: function() {
                                $.ajax({
                                    url: '/Doctor/ViewProfile',
                                    success: function() {
                                        windows.location.reload();
                                    }
                                });
                            }
                        });
                    });
                }
            });
        });
    });


    //file must be of Image type only
    function chkImg() {
        var theFile = document.getElementById('photo_img');
        var filePath = theFile.value;
        var fileExt = /(\.jpg|\.jpeg|\.png)$/i;
        if (!fileExt.exec(filePath)) {
            document.getElementById('errImg').innerHTML = "INCLUDE ONLY IMAGE FILE(i.e., .png, .jpg, .jpeg)";
            document.getElementById('errImg').style.color = "#FF0000";
            theFile.value = '';
            return false;
        }
        else {
            if (theFile.files && theFile.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('prevImg').innerHTML = "<img src='" + e.target.result + "' width='150' />";
                };
                reader.readAsDataURL(theFile.files[0]);
            }
        }
    }
</script>